from prophet import Prophet


class ProphetModel:
    def __init__(self, data):
        """
        Initializes the ProphetModel with a pandas DataFrame.
        The DataFrame must have 'ds' (date) and 'y' (value) columns.
        """
        self._data = data
        self.m = Prophet()
        self.forecast = None

    def perform_forecast(self, periods=365):
        """
        Fits the model and generates a forecast.
        Returns the forecast dataframe.
        """
        self.m.fit(self._data)
        future = self.m.make_future_dataframe(periods=periods)
        self.forecast = self.m.predict(future)
        return self.forecast

    def get_forecast_figure(self):
        """
        Returns the Matplotlib Figure object generated by Prophet.
        This Figure will be passed to the View.
        """
        if self.forecast is not None:
            # The `plot` method of the Prophet object returns a Matplotlib Figure
            fig = self.m.plot(self.forecast)
            return fig
        return None